theme = "nosferatu"

[keys.normal]
C-right = ['move_next_word_start', 'collapse_selection']
C-left = ['move_prev_word_start', 'collapse_selection']
C-up = ['page_cursor_up']
C-down = ['page_cursor_down']

[editor]
auto-save=true
auto-format=true
text-width=80
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
soft-wrap.enable = true
soft-wrap.max-indent-retain=80

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-modification-indicator", "read-only-indicator", "file-name"]
right = ["diagnostics", "position", "position-percentage", "file-type"]
mode.normal = ""
mode.insert = "-- INSERT --"
mode.select = "-- SELECT --"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1
